### ISSUE TITLE
Android: canPrepare and canPlay are always false

### ISSUE THREAD

**Issue by qruzz** [futurice/react-native-audio-toolkit#102]
I am having an issue with the the player on Android .. everything works fine in iOS.

My issue is as stands:
I am creating a new player when the component mounts, and when I log that to the debugger, I am correctly getting a Player object .. however, the canPrepare and canPlay is always false which means that when I call `player.prepare()` or `player.play()` nothing is happening ..
I am not getting any crashes or anything, and I must say that I am a bit baffled by now.
I come from a background of iOS development, so my Android experience is very limited .. and I just can't figure out what I am doing wrong !

```javascript
componentDidMount() {
	const player = new Player(this.props.audioTrack);

	player.prepare((err) => {
		if (err) {
			console.error(err);
		}

		this.setState({
			player,
			totalDuration: player.duration,
		});
	});

	player.play((err) => {
		if (err) {
			console.error(err);
		}

		Animated.timing(this.state.duration, {
			toValue: SCREENHEIGHT,
			duration: player.duration,
		}).start();
	});
}
```

This is what my logs look like:

```javascript
Player {_path: "URL_TO_MY_API", _options: Object, _playerId: 0, _state: 0, _volume: 1…}
	_duration: 5832704
	_lastSync: 1526330167771
	_looping: false
	_options: Object
	_pan: 0
	_path: "URL_TO_MY_API"
	_playerId: 0
	_position: 0
	_state: -1
	_volume: 1
	_wakeLock: false
	canPlay: false
	canPrepare: false
	canStop: (...)
	currentTime: (...)
	duration: 5832704
	isPaused: (...)
	isPlaying: (...)
	isPrepared: (...)
	isStopped: (...)
	looping: (...)
	state: (...)
	volume: (...)
	__proto__: EventEmitter
```

Any help would be highly appreciated!

Kind regards,
Michael

**Comment by KristineTrona** [comment]
Any answer to this? Struggling with the same quetsion now

**Comment by qruzz** [comment]
Ohh, this is well over a year ago and unfortunately the code for this project was handed over to the client. If I recall correctly, I ended up using [react-native-video](https://github.com/react-native-community/react-native-video?ts=2) as it has a "sound-only" version (or at least it had).

The client that I was working for at the time also released that she wanted to play videos through the application anyway, so worked out in my favor.
That unfortunately also means, that I don't have any good answers for you!

**Comment by KristineTrona** [comment]
Well, thanks for the answer anyway :)

**Comment by sbeca** [comment]
The fact that the original post had `_state: -1` in the log means that an error has occurred. Was there no error returned in the callback to `player.prepare()`?

**Comment by KristineTrona** [comment]
In my case this happens on ios:

```
componentDidMount(){
  this.player = new Player(fileName, {
      autoDestroy: false
    }).prepare(err => {
      if (err) {
         console.log('error with preparing Player', err);
      }
    });
}

   this.player.on('error', err => console.log('error with player', err));
```

The logs of player:
```
Player{
    _path: "myRecordingPath.aac" 
    _options: Object, _playerId: 0 
    _state: 1 
    _volume: 1
    _duration: -1
    _events: Object
    _lastSync: -1
    _looping: false
    _options: Object
    _pan: 0
    _path: "myRecordingPath.aac"
    _playerId: 0
    _position: -1
    _state: 1
    _volume: 1
    _wakeLock: false
    canPlay: (...)
    canPrepare: (...)
    canStop: (...)
    currentTime:(...)
    duration: (...)
    isPaused: (...)
    isPlaying: (...)
    isPrepared: (...)
    isStopped: (...)
    looping: (...)
    state: (...)
    volume:(...)
    __proto__: EventEmitter
  }
```

I do not get any error messages. this.player.canPlay and this.player.canPrepare both return false. It looks like it is getting stuck in the 'Preparing' state, but does not throw an error - any idea why would that be the case?

**Comment by sbeca** [comment]
Hi @KristineTrona, I just pushed a potential fix to your issue on iOS in PR #143. Can you please point you test dependency to directly use git://github.com/sbeca/react-native-audio-toolkit.git#master and try again?

**Comment by KristineTrona** [comment]
Thank you @sbeca! I still do not know what actually caused my problem, because I checked and the file did exist, but for some reason everything is working now as it should :)

**Comment by matheusleite** [comment]
The same problem here

**Comment by ansal-exp** [comment]
Same problem here too. Any solutions or proposals to fix are also welcome or at least some forks with a resolution would be helpful.

**Comment by mrigo** [comment]
Any update on this? Android only!
Please, any help or solutions are so welcome!

**Comment by asavardplante** [comment]
I'm still having this issue, any fixes?

**Comment by farhankassam2** [comment]
Okay so I also am experiencing this issue in Android currently. It is not nice how such a widely used library is not well maintained, particularly for an issue this large that should be given priority. 

My issue is similar to what the initial author who opened this ticket was experiencing. In my code, I conditionally render the play button only when the player can play, by calling `this._player.canPlay`. In the screenshot below, you will see that my `_player` is defined with the correct path and options, state is not -1 and the playerID is correctly defined to be 0. Yet, the `.canPlay` function produces a `false`:
<img width="1523" alt="Screen Shot 2020-07-18 at 12 02 53 PM" src="https://user-images.githubusercontent.com/22672953/87860142-e43a8200-c8ef-11ea-88a4-140e7e6c3210.png">
<img width="472" alt="Screen Shot 2020-07-18 at 12 14 51 PM" src="https://user-images.githubusercontent.com/22672953/87860186-53b07180-c8f0-11ea-9a38-906fba15ec38.png">



What constitutes the player to be able to play? Is it when it is prepared (i.e. `.prepare` has been called on it?). Or is it when it has a valid path to stream audio from? For both the above conditions, I have tested it and `.canPlay` never turns to `true` in either case. Evidently, it is a problem faced by many. Can this be fixed soon?

Additional information:
Package version: `@react-native-community/audio-toolkit: ^2.0.3`
Android API: 28
NPM version: 6.13.4
Node version: v12.14.1

**Comment by disrae** [comment]
I think we are having this exact issue. No work arounds?

**Comment by tronin** [comment]
The same bug
